name: Invite user to teams

on:
  issue_comment:
    types: [created]

jobs:
  invite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repository
        uses: farhanashrafdev/checkout@v2
        with:
          ref: main # specify the branch or tag you want to use


      - name: Install dependencies
        run: npm install @octokit/core @octokit/rest @octokit/plugin-rest-endpoint-methods @octokit/plugin-paginate-rest @octokit/plugin-request-log

      - name: Invite user to teams
        uses: actions/github-script@0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            
            async function inviteToTeam(teamName) {
              const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
              
              try {
                const teamId = await octokit.teams.getByName({
                  org: "Devconnect-tech",
                  team_slug: teamName
                }).then(({data}) => data.id)
                await octokit.teams.addOrUpdateMembership({
                  team_id: teamId,
                  username: context.payload.comment.user.login
                })
                console.log(`User ${context.payload.comment.user.login} has been added to team ${teamName}`)
              } catch (error) {
                console.error(`Error inviting user to team: ${error}`)
              }
            }
            
            const comment = context.payload.comment.body
            const teamName = (() => {
              switch (true) {
                case comment.includes("@addme_Cloud"):
                  return "Cloud"
                case comment.includes("@addme_Cyber Warriors"):
                  return "Cyber Warriors"
                case comment.includes("@addme_DevOps"):
                  return "DevOps"
                case comment.includes("@addme_Flutter"):
                  return "Flutter"
                case comment.includes("@addme_Lets-React"):
                  return "Lets-React"
                case comment.includes("@addme_MAC"):
                  return "MAC"
                default:
                  return null
              }
            })()
            
            if (teamName) {
              await inviteToTeam(teamName)
            }
