name: Invite user to teams

on:


jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install PyGithub
          
      - name: Invite user to teams
        uses: actions/github-script@0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const {Github} = require("@octokit/rest");
            
            function invite_to_team(team_name) {
                const g = new Github({auth: `token ${process.env.GITHUB_TOKEN}`});
                const org = g.getOrganization("Devconnect-tech");
                const team = org.getTeamBySlug(team_name);
                team.inviteUser(context.payload.comment.user.login);
                console.log(`User ${context.payload.comment.user.login} has been added to team ${team_name}`);
            }
            
            const comment = context.payload.comment.body;
            if (comment.includes("@addme_Cloud")) {
                invite_to_team("Cloud");
            } else if (comment.includes("@addme_Cyber Warriors")) {
                invite_to_team("Cyber Warriors");
            } else if (comment.includes("@addme_DevOps")) {
                invite_to_team("DevOps");
            } else if (comment.includes("@addme_Flutter")) {
                invite_to_team("Flutter");
            } else if (comment.includes("@addme_Lets-React")) {
                invite_to_team("Lets-React");
            } else if (comment.includes("@addme_MAC")) {
                invite_to_team("MAC");
            }
