name: Invite user to teams

 branches:
    only:
      - testing

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install PyGithub
          
      - name: Invite user to teams
        uses: actions/github-script@0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            from github import Github
            
            def invite_to_team(team_name):
                g = Github(process.env.GITHUB_TOKEN)
                org = g.get_organization("Devconnect-tech")
                team = org.get_team_by_slug(team_name)
                team.invite_user(context.payload.comment.user.login)
                print(f"User {context.payload.comment.user.login} has been added to team {team_name}")
                
            comment = context.payload.comment.body
            if "@addme_" in comment:
                if "@addme_Cloud" in comment:
                    invite_to_team("Cloud")
                if "@addme_Cyber Warriors" in comment:
                    invite_to_team("Cyber Warriors")
                if "@addme_DevOps" in comment:
                    invite_to_team("DevOps")
                if "@addme_Flutter" in comment:
                    invite_to_team("Flutter")
                if "@addme_Lets-React" in comment:
                    invite_to_team("Lets-React")
                if "@addme_MAC" in comment:
                    invite_to_team("MAC")