on:
  issues:
    types: invite

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: Devconnect-tech
          label: invite me to the DevConnect-tech organization, we are very happy to have you here!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Org.'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
